apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train
  name: train-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: cont1
        image: rajeshr3f16/train:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trainsvc
spec:
  type: LoadBalancer
  selector:
    app: train
  ports:
    - port: 80
